### ISSUE TITLE
Is this project functional or approaching functionality? 

### ISSUE THREAD

**Issue by nilvon9wo** [coveooss/sfdx4csharp#22]
I'm looking to create a Function App in C# with a timer trigger which will occasionally (e.g. once per day) manipulate our Salesforce environment via SFDX.  Specific tasks may (will) include:

1. (Re)setting trace flags for Users and Apex Classes.
2. Downloading the debug logs so they can be persisted (and searched).

Presently, I'm trying to figure out how to get C# to leverage Sfdx.
I'm hoping to do this without reinventing too many wheels.
I stumbled upon your project.

But it doesn't seem to be 1.0 or higher and last commit was a year ago.
Moreover, the documentation is sparse and what is there is saying to do things with NPM, even though this is nominally a C# project?

It would be great to have some clarification whether this project is fit for any purpose, and if so, to see some examples how it may be used.

**Comment by dshelgunov** [comment]
Better late that never they say 😅 Yes, this project is actively used by our own platform. I edited the description to include that this project is distributed via nuget. For more details, import it to your c# project and follow the new examples I added to the README. There is also now documentation included in the nuget package.
